bookstore_app/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookstore_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookstore_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookstore_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

bookstore_app/app/helpers/application_helper.rb
module ApplicationHelper
end

bookstore_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

bookstore_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookstoreApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

  <h5 class="my-0 mr-md-auto font-weight-normal"> Sheffield Bookstore </h5>

  <nav class="my-2 my-md-0 mr-md-3">


    <a class="p-2 text-dark" href="#"> <%= link_to "Home", 'home' %> </a>
    <a class="p-2 text-dark" href="#"> <%= link_to "About Us", 'about' %> </a>
    <a class="p-2 text-dark" href="#"> <%= link_to "Contact Us", 'contact' %> </a>
    <a class="p-2 text-dark" href="#"> <%= link_to "Add New Book", new_book_path %> </a>

   
  </nav>

  

</div>

  <div class="container">

  <%= yield %>

  </div>
    
  </body>

</html>

bookstore_app/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

bookstore_app/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

bookstore_app/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<div class="container">
 <h1 class="jumbotron-heading">Album example</h1>
<div class="container">
 <div class="row">
 <div class="col">
 <p>Lorem ipsum dolor sit amet, labore copiosae at sed, animal denique scaevola usu ad. Est tamquam adversarium ea. Eam id placerat perpetua consectetuer, gloriatur forensibus et per. Vim ut utinam salutandi, vide interpretaris at usu. Eu vim enim vide minimum, sed tota propriae at, sint prima ad cum.

 Et aperiri labitur intellegebat vix, mei et case veri recteque, in sed decore deserunt. Vide ludus voluptaria ut mea, vel volumus suscipiantur ne. Quod veniam melius sea an. Delenit atomorum cu quo, eu pri bonorum convenire. Est graeco utroque temporibus cu, timeam detraxit assueverit mei an.
 
 Fugit commune eligendi at vix, at utinam epicurei dissentiunt his. Quo no fugit ornatus reprimique. Ex eum modus malorum qualisque, vim ne dicat postea. At has mucius postulant vulputate. Ex saepe iracundia sed. Ius detracto posidonium at, regione vivendum postulant usu no.
 
 An eam tempor persequeris, vim tollit bonorum dolorem ne. Tacimates eleifend dissentiunt at mei. Mel te dico ludus impedit, eam nisl sale efficiantur eu. Ex vix erant vitae. Exerci aliquip his eu.
 
 Sumo iudico ei sit. Ne eros verterem intellegat est, vel quod consequat ne. Veniam virtute laboramus no his, mea verear electram cu. Mel cu movet iudico, qui persius mediocrem an, tale solet graecis eos no. Nec eu adolescens dissentiunt theophrastus, at has zril viderer. </p>
 </div>
 <div class="col">
 <p> Lorem ipsum dolor sit amet, labore copiosae at sed, animal denique scaevola usu ad. Est tamquam adversarium ea. Eam id placerat perpetua consectetuer, gloriatur forensibus et per. Vim ut utinam salutandi, vide interpretaris at usu. Eu vim enim vide minimum, sed tota propriae at, sint prima ad cum.

 Et aperiri labitur intellegebat vix, mei et case veri recteque, in sed decore deserunt. Vide ludus voluptaria ut mea, vel volumus suscipiantur ne. Quod veniam melius sea an. Delenit atomorum cu quo, eu pri bonorum convenire. Est graeco utroque temporibus cu, timeam detraxit assueverit mei an.
 
 Fugit commune eligendi at vix, at utinam epicurei dissentiunt his. Quo no fugit ornatus reprimique. Ex eum modus malorum qualisque, vim ne dicat postea. At has mucius postulant vulputate. Ex saepe iracundia sed. Ius detracto posidonium at, regione vivendum postulant usu no.
 
 An eam tempor persequeris, vim tollit bonorum dolorem ne. Tacimates eleifend dissentiunt at mei. Mel te dico ludus impedit, eam nisl sale efficiantur eu. Ex vix erant vitae. Exerci aliquip his eu.
 
 Sumo iudico ei sit. Ne eros verterem intellegat est, vel quod consequat ne. Veniam virtute laboramus no his, mea verear electram cu. Mel cu movet iudico, qui persius mediocrem an, tale solet graecis eos no. Nec eu adolescens dissentiunt theophrastus, at has zril viderer.</p>
 </div>
 </div></div>